version: '3.9'
services:
  rabbitmq:
    container_name: 001-rabbitmq
    image: rabbitmq:3.12.4-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - invoice-manager

  openzipkin:
    container_name: 002-zipkin
    image: openzipkin/zipkin:2.24.3
    ports:
      - '9411:9411'
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      STORAGE_TYPE: mem
    networks:
      - invoice-manager

  db-ms-client:
    container_name: 003-db-ms-client
    image: mysql:8.1
    restart: on-failure
    ports:
      - '${DB_MS_CLIENT_PORT}:${DB_MS_CLIENT_PORT}'
    volumes:
      - mysql_data_ms_client:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: ${DB_MS_CLIENT_PORT}
      MYSQL_DATABASE: ${DB_MS_CLIENT_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - invoice-manager

  db-ms-email:
    container_name: 004-db-ms-email
    image: mysql:8.1
    restart: on-failure
    ports:
      - '${DB_MS_EMAIL_PORT}:${DB_MS_EMAIL_PORT}'
    volumes:
      - mysql_data_ms_email:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: ${DB_MS_EMAIL_PORT}
      MYSQL_DATABASE: ${DB_MS_EMAIL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - invoice-manager

  db-ms-electronic-invoice:
    container_name: 005-db-ms-electronic-invoice
    image: mysql:8.1
    restart: on-failure
    ports:
      - '${DB_MS_ELECTRONIC_INVOICE_PORT}:${DB_MS_ELECTRONIC_INVOICE_PORT}'
    volumes:
      - mysql_data_ms_electronic_invoice:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: ${DB_MS_ELECTRONIC_INVOICE_PORT}
      MYSQL_DATABASE: ${DB_MS_ELECTRONIC_INVOICE_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - invoice-manager

  db-ms-tax-calculator:
    container_name: 006-db-ms-tax-calculator
    image: mysql:8.1
    restart: on-failure
    ports:
      - '${DB_MS_TAX_CALCULATOR_PORT}:${DB_MS_TAX_CALCULATOR_PORT}'
    volumes:
      - mysql_data_ms_tax_calculator:/var/lib/mysql
    environment:
      MYSQL_TCP_PORT: ${DB_MS_TAX_CALCULATOR_PORT}
      MYSQL_DATABASE: ${DB_MS_TAX_CALCULATOR_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - invoice-manager

  service-registry:
    container_name: 007-service-registry
    image: service-registry:1.0.0
    env_file:
      - /service-registry/.env
    ports:
      - '8081:8081'
    networks:
      - invoice-manager

  service-auth:
    container_name: 008-service-auth
    image: service-auth:1.0.0
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-ms-client:${DB_MS_CLIENT_PORT}/${DB_MS_CLIENT_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:  http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
    env_file:
      - /service-auth/.env
    ports:
      - '9000:9000'
    networks:
      - invoice-manager
    depends_on:
      - service-registry
      - db-ms-client

  service-gateway:
    container_name: 009-service-gateway
    image: service-gateway:1.0.0
    restart: on-failure
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
    env_file:
      - /service-gateway/.env
    ports:
      - '8080:8080'
    depends_on:
      - service-registry
      - service-auth
      - db-ms-client
      - ms-client
      - ms-email
      - ms-electronic-invoice
      - db-ms-tax-calculator
      - rabbitmq
    networks:
      - invoice-manager

  ms-client:
    container_name: 010-ms-client
    image: ms-client:1.0.0
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-ms-client:${DB_MS_CLIENT_PORT}/${DB_MS_CLIENT_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
    env_file:
      - /ms-client/.env
    ports:
      - '8083:8083'
    depends_on:
      - service-registry
      - db-ms-client
      - rabbitmq
    networks:
      - invoice-manager

  ms-email:
    container_name: 011-ms-email
    image: ms-email:1.0.0
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-ms-email:${DB_MS_EMAIL_PORT}/${DB_MS_EMAIL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:  http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING_RABBITMQ_HOST: rabbitmq
    env_file:
      - /ms-email/.env
    ports:
      - '8084:8084'
    depends_on:
      - service-registry
      - service-auth
      - db-ms-email
      - rabbitmq
    networks:
      - invoice-manager

  ms-electronic-invoice:
    container_name: 012-ms-electronic-invoice
    image: ms-electronic-invoice:1.0.0
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-ms-electronic-invoice:${DB_MS_ELECTRONIC_INVOICE_PORT}/${DB_MS_ELECTRONIC_INVOICE_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    env_file:
      - /ms-electronic-invoice/.env
    ports:
      - '8085:8085'
    depends_on:
      - service-registry
      - service-auth
      - db-ms-electronic-invoice
    networks:
      - invoice-manager

  ms-tax-calculator:
    container_name: 013-ms-tax-calculator
    image: ms-tax-calculator:1.0.0
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-ms-tax-calculator:${DB_MS_TAX_CALCULATOR_PORT}/${DB_MS_TAX_CALCULATOR_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@service-registry:8081/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    env_file:
      - /ms-tax-calculator/.env
    ports:
      - '8086:8086'
    depends_on:
      - service-registry
      - service-auth
      - db-ms-tax-calculator
    networks:
      - invoice-manager

volumes:
  mysql_data_ms_client:
  mysql_data_ms_email:
  mysql_data_ms_electronic_invoice:
  mysql_data_ms_tax_calculator:

networks:
  invoice-manager:
    driver: bridge

