server:
  port: 8084

spring:
  application:
    name: ms-email
  config:
    import: optional:file:ms-email/.env[.properties]
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}

management:
  tracing:
    sampling:
      probability: 1.0

security:
  service-auth:
    username: ${SERVICE_AUTH_USERNAME}
    password: ${SERVICE_AUTH_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

queues:
  notification: ms-email.v1.send-email

springdoc:
  show-actuator: true
