server:
  port: 8585

spring:
  application:
    name: ms-email
  config:
    import: optional:file:ms-email/.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    addresses: ${AMQP_URL}
    queue: ${AMQP_MS_EMAIL_QUEUE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}