spring:
  application:
    name: ms-tax-calculator
  config:
    import: optional:file:ms-tax-calculator/.env[.properties]
    profiles:
      active: dev

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

springdoc:
  show-actuator: true
