server:
  port: 8086

spring:
  application:
    name: ms-tax-calculator
    allow-bean-definition-overriding: true
  config:
    import: optional:file:ms-tax-calculator/.env[.properties]
    profiles:
      active: dev
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: MSTaxCalculatorRateLimit
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 60
              unit: seconds

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

springdoc:
  show-actuator: true
