server:
  port: 0

spring:
  application:
    name: ms-client
  config:
    import: optional:file:ms-client/.env[.properties]
    uri: http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

queues:
  notification: ms-email.v1.send-email
