server:
  port: 8083

spring:
  application:
    name: ms-client
    allow-bean-definition-overriding: true
  config:
    import: optional:file:ms-client/.env[.properties]
    uri: http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: MSClientRateLimit
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 60
              unit: seconds

management:
  tracing:
    sampling:
      probability: 1.0

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

queues:
  notification: ms-email.v1.send-email

springdoc:
  show-actuator: true
