server:
  port: 0

spring:
  application:
    name: ms-client
  config:
    import: optional:file:ms-client/.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}