server:
  port: 0

spring:
  application:
    name: ms-client
  config:
    import:
      - optional:file:ms-client/.env[.properties]
      - optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}