server:
  port: 8082

spring:
  application:
    name: service-gateway
  config:
    import: optional:file:service-gateway/.env[.properties]
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}