server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: service-gateway
  config:
    import: optional:file:service-gateway/.env[.properties]
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/ms-client/**
        - id: ms-email
          uri: lb://ms-email
          predicates:
            - Path=/ms-email/**
        - id: ms-electronic-invoice
          uri: lb://ms-electronic-invoice
          predicates:
            - Path=/ms-electronic-invoice/**
        - id: ms-tax-calculator
          uri: lb://ms-tax-calculator
          predicates:
            - Path=/ms-tax-calculator/**
        - id: openapi
          uri: lb://service-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}
