ALTER TABLE managers
ADD COLUMN enabled BOOLEAN DEFAULT TRUE,
ADD COLUMN account_non_expired BOOLEAN DEFAULT TRUE,
ADD COLUMN account_non_locked BOOLEAN DEFAULT TRUE,
ADD COLUMN credentials_non_expired BOOLEAN DEFAULT TRUE,
ADD COLUMN createdAt DATETIME NOT NULL,
ADD COLUMN updatedAt DATETIME DEFAULT NULL;
