server:
  port: 8085

spring:
  application:
    name: ms-electronic-invoice
    allow-bean-definition-overriding: true
  config:
    import: optional:file:ms-electronic-invoice/.env[.properties]
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USERNAME}
    password: ${AMQP_PASSWORD}
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml

bucket4j:
  enabled: true
  filters:
    - cache-name: MSElectronicInvoiceRateLimit
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 60
              unit: seconds

management:
  tracing:
    sampling:
      probability: 1.0

security:
  secret-key: ${CODE_SECRET_KEY}
  service-auth:
    username: ${SERVICE_AUTH_USERNAME}
    password: ${SERVICE_AUTH_PASSWORD}

queues:
  notification: ms-email.v1.send-email

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

springdoc:
  show-actuator: true

resilience4j:
  circuitbreaker:
    instances:
      cb_ms-client:
        minimumNumberOfCalls: 4
        SlidingWindowSize: 8