spring:
  application:
    name: ms-electronic-invoice
  config:
    import: optional:file:ms-electronic-invoice/.env[.properties]
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

management:
  tracing:
    sampling:
      probability: 1.0

security:
  secret-key: ${CODE_SECRET_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

springdoc:
  show-actuator: true